---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "expressapiapp"
  namespace: "default"
  labels:
    app: "expressapiapp"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "expressapiapp"
  template:
    metadata:
      labels:
        app: "expressapiapp"
    spec:
      containers:
      - name: "myimage-sha256-1"
        image: "us-east1-docker.pkg.dev/nickgketerraformdemoproject/my-repository/myimage:latest"        
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "expressapiapp-service"
  namespace: "default"
  labels:
    app: "expressapiapp"
spec:
  ports:
  - protocol: "TCP"
    port: 80
  selector:
    app: "expressapiapp"
  type: "LoadBalancer"
  loadBalancerIP: ""
