---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "expressapiapp"
  namespace: "default"
  labels:
    app: "expressapiapp"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "expressapiapp"
  template:
    metadata:
      labels:
        app: "expressapiapp"
    spec:
    # #serviceaccountname
    #   volumes:
    #   - name: secret-volume
    #     secret:
    #       secretName: big_query_service_account
      containers:
      - name: "expressapiapp"
        image: "us-east1-docker.pkg.dev/nickgketerraformdemoproject/my-repository/myimage:latest"   
        envFrom:
        - configMapRef:
            name: gke-terraform-config 
        ports:
        - containerPort: 8080   
        # volumeMounts:
        # - name: secret-volume
        #   readOnly: true
        #   mountPath: "/etc/secret-volume"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "expressapiapp-service"
  namespace: "default"
  labels:
    app: "expressapiapp"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8080
  selector:
    app: "expressapiapp"
  type: "LoadBalancer"
  loadBalancerIP: ""
